### ISSUE TITLE
Voting Issue

### ISSUE THREAD

**Issue by ssnam90** [nutbox-dao/peanut-interface-v2#12]
Although Account name @ssnam90 is Amount (SP) 65,641.622, Shares (MV) 124.153,
What is the reason you are voting at 0.64% weight?

![11](https://user-images.githubusercontent.com/80802341/111409599-9bef9000-871a-11eb-8ba8-3943376f09c3.jpg)
![12](https://user-images.githubusercontent.com/80802341/111409601-9d20bd00-871a-11eb-95a2-373d7618b6a0.jpg)
![13](https://user-images.githubusercontent.com/80802341/111409603-9db95380-871a-11eb-8dce-ca6bfd8de805.jpg)
![14](https://user-images.githubusercontent.com/80802341/111409604-9e51ea00-871a-11eb-82ef-d0a3626ae8d9.jpg)

**Comment by terryyyyyy** [comment]
@ssnam90 You add delegate today, But the voting weight is calculated by your delegation before.It will be recalculat this midnight,So the post you publish tomorrow will get the new voting weight.This is the right process.

**Comment by terryyyyyy** [comment]
And if the voting weight is right tomorrow.Could you close this issue?

**Comment by ssnam90** [comment]
> And if the voting weight is right tomorrow.Could you close this issue?
The point of the question is that the voting at 0.64% weight was even over 64,000 Amount (SP) 2-3 days ago.
