### ISSUE TITLE
当登录了steem后。进入nutbox质押挖矿，代理挖矿会一直闪烁并不提示做任何操作

### ISSUE THREAD

**Issue by boylikegirl** [nutbox-dao/peanut-interface-v2#13]
![image](https://user-images.githubusercontent.com/4484831/111486237-4777ff00-8772-11eb-82c3-48562276e669.png)

当再次解锁TRON后。代理按钮正常显示。

地址：TUXG9zbQHsbsmAxfj9e3jDLRBFEEAD1Sp7

**Comment by tolak** [comment]
cc @terryyyyyy I think this issue duplicate with issue #8

**Comment by terryyyyyy** [comment]
@boylikegirl Now , I have fixed the issue ,you can check it on test.nutbox.io.
