### ISSUE TITLE
Account name @ssnam90, Staking Mining does not allow additional delegation.

### ISSUE THREAD

**Issue by ssnam90** [nutbox-dao/peanut-interface-v2#14]
Account name @ssnam90, Staking Mining does not allow additional delegation.

Nutbox.io steem power delegated 64,655.372

What is the reason?

Also, if you check on Steemworld, Account name @ssnam90 is Amount (SP) 65,655.432, Shares (MV) 124.153, why are the values ​​different?

Question 1
Why isn't there an additional delegation in Staking Mining on Nutbox.io?

Question 2
Steemworld’s delegation value and
Why are Nutbox.io's Staking Mining delegation values ​​different?

The gas cost was still paid.

![11](https://user-images.githubusercontent.com/80802341/111718619-9ec6be00-889d-11eb-86d7-a0d9e7aac1f9.jpg)
![12](https://user-images.githubusercontent.com/80802341/111718632-a4240880-889d-11eb-919b-83b9e098eec2.jpg)
![13](https://user-images.githubusercontent.com/80802341/111718638-a6866280-889d-11eb-96cf-5745dff3e7b8.jpg)
![14](https://user-images.githubusercontent.com/80802341/111718644-a8502600-889d-11eb-8464-649569dc016b.jpg)

**Comment by terryyyyyy** [comment]
The same issue with #9. We are trying to fix it.
