### ISSUE TITLE
<bug brief> Problems with delegation when harvesting PNUT

### ISSUE THREAD

**Issue by leonelb11** [nutbox-dao/peanut-interface-v2#15]
<bug details>

I was recently thinking of using the "upvote" feature and burning 1000 pnut on one of my posts. I had about 600 pnut in my trx wallet and a little over 500 pnut mined so far. Before withdrawing it and burning the 1000 pnut, I made a delegation to nutbox to have 700 sp mining and not 201 that I posted days ago. 

![image](https://user-images.githubusercontent.com/80784330/111926268-94b1e480-8a82-11eb-80ea-cca9d9c4af4c.png)

![image](https://user-images.githubusercontent.com/80784330/111926283-9bd8f280-8a82-11eb-8fc9-c839564dc45f.png)

After doing the delegation, I removed the 562 pnut I had mined.

![image](https://user-images.githubusercontent.com/80784330/111926319-c5921980-8a82-11eb-92ef-8c61e6d23f15.png)

![image](https://user-images.githubusercontent.com/80784330/111926352-e78b9c00-8a82-11eb-8970-b6be45c6a16f.png)

![image](https://user-images.githubusercontent.com/80784330/111926472-510baa80-8a83-11eb-9871-f18cb51f6d88.png)

But, my delegation went back down to 201 sp. 

![image](https://user-images.githubusercontent.com/80784330/111926519-7a2c3b00-8a83-11eb-8abf-8fff9a64c2f7.png)

![image](https://user-images.githubusercontent.com/80784330/111926571-beb7d680-8a83-11eb-8ce4-0337963456f2.png)

I delegated 201 a few days ago at @terryyyyyy request to test if I was still having problems delegating.

I hope you can help me. Thank you very much for your work.

address:TV1HUGWuFycuugcoaasVZiBJ9Mktf4weoB

name in steemit: @leonelb

**Comment by terryyyyyy** [comment]
Hi, this is the same issue listed on #9. We are trying to solve it. Your transaction on tron is fail.So the creasing delegation isn't effect. As a remedy, you can add 501 sp for try.
And i will close this issue.I will patse news on issue #9
