### ISSUE TITLE
当在质押流动挖矿菜单时，未连接钱包点击MAX出现-1，当交换兑换位置后。点击MAX出现0。

### ISSUE THREAD

**Issue by boylikegirl** [nutbox-dao/peanut-interface-v2#16]
![image](https://user-images.githubusercontent.com/4484831/111952996-f032af80-8b20-11eb-942c-2003fbefa42c.png)

如图。
从优化用户体验的角度讲。
是否可以在未连接钱包时。点击Max ，给出提示请先连接钱包。

地址：TUXG9zbQHsbsmAxfj9e3jDLRBFEEAD1Sp7

**Comment by terryyyyyy** [comment]
Yes, I think your advice is good

**Comment by terryyyyyy** [comment]
@boylikegirl  It's ok now.Please close this issue.
