### ISSUE TITLE
steem转tsteem时的问题

### ISSUE THREAD

**Issue by lemooljiang** [nutbox-dao/peanut-interface-v2#18]
steem转tsteem时如果没有解锁tron钱包也可以成功发送，但结果却会出错！因为没有获取tron地址导致无法生成tsteem。这在逻辑上要做修改，在发送前要判断是否已获取tron地址。

**Comment by terryyyyyy** [comment]
Yes, I have fixed it. It will show connect btn if user dont get tron address.
