### ISSUE TITLE
前端显示PNUT价格和个人的产出量

### ISSUE THREAD

**Issue by lemooljiang** [nutbox-dao/peanut-interface-v2#19]
前端显示PNUT价格（中文的换算成人民币，英文的用美元），和个人的产出量（表中的 debtRewards 参数）。
例如： 
PNUT价格：￥0.38， 已收获 23,562(￥8,953.56)，未收获 6,200 (￥2,356)

**Comment by terryyyyyy** [comment]
It's a good idea.
