### ISSUE TITLE
解决增加SP代理时的错误操作

### ISSUE THREAD

**Issue by lemooljiang** [nutbox-dao/peanut-interface-v2#21]
错误问题：steem成功而tron失败，两边的代理量不一致。增减操作时容易出现错误。
解决思想：此时前端做增减代理时应以steem链上的代理为起始值！代理后的显示也要读取tron上的数据。如果出现代理失败，用户可以直接增减相应的代理量。

代码： `ChangeDelegateMask.vue` 中将 `delegatedSp`替换成 `delegatedSpFromSteem`, 获取方法如下，
async getDelegateFromSteem(){
          let user = 'lemooljiang'
          let res = await this.steem.api.getVestingDelegationsAsync(user, 'nutbox.mine', 1) 
          let delegatedSpFromSteem = res[0].vesting_shares / spToVests 
 }

**Comment by terryyyyyy** [comment]
It's ok now
