### ISSUE TITLE
Voting issue

### ISSUE THREAD

**Issue by ssnam90** [nutbox-dao/peanut-interface-v2#22]
My Steemit account is @ssnam90.

Nutbox.mine did not vote for my post below.

https://steemit.com/hive-160196/@ssnam90/6zzlnd

Created : 2021-05-11, 06:05

This issue occurred after using the upvoting service provided by Nutbox.mine for my other postings.

Other than that, nothing has changed.

![11](https://user-images.githubusercontent.com/80802341/117830322-7ca25880-b2ae-11eb-98a0-5c7f1cde8b97.jpg)

![12](https://user-images.githubusercontent.com/80802341/117830385-8926b100-b2ae-11eb-98a8-e8643658d5cd.jpg)

I ask for a solution to the issue.

**Comment by tolak** [comment]
It's better to ask us in discord channels rather than open an issue here.
