### ISSUE TITLE
SP total needed for purchasing upvote inaccurate

### ISSUE THREAD

**Issue by jondoe7** [nutbox-dao/peanut-interface-v2#28]
The amount of SP needed to purchase an upvote is 800 SP, not 600 SP. I delegated 600 SP and attempted to purchase an upvote several times. The purchase was rejected each time. I then raised my delegation to 800 SP and attempted again and it worked just fine. Please change the amount of SP needed to 600 SP or update the info section to mention 800 SP instead of 600 SP.

0x1D06CE5C866454206aC45a32FEaaeCb5775789B9

**Comment by terryyyyyy** [comment]
Thanks for your remind, we have set the param to 600SP.
