### ISSUE TITLE
No TRX was needed to purchase upvote

### ISSUE THREAD

**Issue by jondoe7** [nutbox-dao/peanut-interface-v2#29]
I attempted to purchase several upvotes and each time no TRX was needed for the transaction. The directions state that roughly 10 TRX is needed for the transaction to go through, but after several tests it appears no TRX is needed at all. Please remove the portion about needing TRX from the upvote buying directions.

0x1D06CE5C866454206aC45a32FEaaeCb5775789B9

**Comment by PNCTRX** [comment]
Passive Income , Proven Project! TRXUSDT
https://38trx.com/m/register  Sign-up bonus: 9999TRX
5trx minimum deposit 3%, maximum return 9%
Refer friends to recharge to get 20% of the recharge funds,Immediate withdrawal Immediate credit,
elegram Customer Service:https://t.me/PNC_TRX

**Comment by terryyyyyy** [comment]
Yes, It's our fault, we have fix the post.
