### ISSUE TITLE
i18n: Mixed Chinese + English message display 

### ISSUE THREAD

**Issue by think-in-universe** [nutbox-dao/peanut-interface-v2#3]
In Staking page, most text are displayed in Chinese while several labels are in English. 

![image](https://user-images.githubusercontent.com/46699230/110412717-987b5980-80c7-11eb-8103-e7a2406e4c80.png)

e.g. earned, delegated, staked in above screenshot.

Is this designed by purpose? and what's the benefit of not translating these labels?

**Comment by terryyyyyy** [comment]
Yes, it's desgned like that. We think these simple word can show simple and clear info to people. And the UI will looks good.
