### ISSUE TITLE
Impossible to mine both PNUT and NUT simultaneously

### ISSUE THREAD

**Issue by jondoe7** [nutbox-dao/peanut-interface-v2#30]
When I delegated SP to Peanut it enabled me to start earning PNUT, however, it stopped the earning of NUTS. Then when I went to update the SP delegation on Walnut, I started earning NUT but it stopped the earning of PNUT. Basically it only allows a user to earn either PNUT or NUT, but not both at the same time.

0x1D06CE5C866454206aC45a32FEaaeCb5775789B9

**Comment by terryyyyyy** [comment]
Yes, in walnut network, you can only join one steem delegatee pool.
