### ISSUE TITLE
Success should not be a warning?

### ISSUE THREAD

**Issue by tomoyan** [nutbox-dao/peanut-interface-v2#31]
![image](https://user-images.githubusercontent.com/3170452/160244850-413372e6-53f1-4bea-963e-7905b3e9de57.png)

Buy vote feature worked so this is not really a bug? but this feels like not success... to me this is an error and something went wrong.
![image](https://user-images.githubusercontent.com/3170452/160245008-afba6589-fd20-4d69-a291-2378a9547ce9.png)

Success is more green and nice indicator? not "!"

0xb254cEEE734F3B3372fb43359294C54391a66f2E

**Comment by terryyyyyy** [comment]
Yes, I have update the icon.

**Comment by tomoyan** [comment]
0xb254cEEE734F3B3372fb43359294C54391a66f2E
