### ISSUE TITLE
UI: Docs icon is quite similar to a Trash Bin icon

### ISSUE THREAD

**Issue by think-in-universe** [nutbox-dao/peanut-interface-v2#4]
### Problem

In the left sidebar, it's confusing what the 3rd icon is at first glance. 

It looks like a trash bin in some system, and don't remind me of docs.

the doc icon
![image](https://user-images.githubusercontent.com/46699230/110412911-f14af200-80c7-11eb-802f-5375a27e9585.png)

v.s. 

trash icon (from https://fontawesome.com/cheatsheet)

![image](https://user-images.githubusercontent.com/46699230/110412977-0c1d6680-80c8-11eb-94f2-24a48687e96a.png)

### Solution

Personally I would prefer book (from https://fontawesome.com/cheatsheet) comparing to the current one

![image](https://user-images.githubusercontent.com/46699230/110413112-4555d680-80c8-11eb-9200-bcb52ae1a6aa.png)

**Comment by terryyyyyy** [comment]
The new icon will be set
![image](https://user-images.githubusercontent.com/15071907/110421720-03815c00-80d9-11eb-95d2-c6b95601d08e.png)
