### ISSUE TITLE
UI: improve the Wallet buttons

### ISSUE THREAD

**Issue by think-in-universe** [nutbox-dao/peanut-interface-v2#5]
### Description

The dash in the button looks not good. 

![image](https://user-images.githubusercontent.com/46699230/110413386-b85f4d00-80c8-11eb-89a7-138764f476d5.png)

May replace **Steem-Keychain** with **Steem Keychain**, and replace **tron-link** with **TronLink**

**Comment by terryyyyyy** [comment]
It will be fixed

**Comment by terryyyyyy** [comment]
It's ok now
