### ISSUE TITLE
BUG increasing delegation.

### ISSUE THREAD

**Issue by alearisteguieta** [nutbox-dao/peanut-interface-v2#9]
Hi team i find this bug. Today i want to increase my delegation, i increase 200 SP, i pay my 1 steem comision and validity the transaction in the Steem Keychain. But see the numbers of the Nutbox UI. I have 1011 SP and i put 200 SP total = 1211 SP but the page only show 1011 SP  
The number of coins I have mined is not shown either.
![image](https://user-images.githubusercontent.com/79173697/111006559-6423c980-8363-11eb-868d-de5c910a237b.png)

See my proof of delegation in Steemworld 
![image](https://user-images.githubusercontent.com/79173697/111006656-946b6800-8363-11eb-8936-4e72864d1f73.png)

If i refresh the page, now i see my mined PNUT but my delegation not increase. 
![image](https://user-images.githubusercontent.com/79173697/111008062-ab5f8980-8366-11eb-9f6e-b9204fc0c286.png)

Here my fee for delegation 
![image](https://user-images.githubusercontent.com/79173697/111014750-a2c57e00-837b-11eb-8ed7-155a37fe3d3e.png)

I think this is a big bug, because as you can see the transaction within steemit is done, but on the Nutbox page there are no results. The delegation is the same, it should increase to 1211 SP 

Address: 
TQhe7ruXm96KfPBP3C5UdJpLU7n5Fijffv

steemit ID: @ale.aristeguieta

**Comment by tolak** [comment]
Looks like our Steem bridge missed that transaction. cc@think-in-universe

**Comment by alearisteguieta** [comment]
> Looks like our Steem bridge missed that transaction. cc@think-in-universe

Well i speak with the team and the problem is solved. I await for the reward. Thanks!

**Comment by think-in-universe** [comment]
The below error message was received when performing staking for the transaction.

It's probably caused by the recently introduced API key by tronweb, and it seems to be kind of random issue that is hard to predict the error message in long run. 

```
Failed when processing the action [
  'delegate_vesting_shares',
  {
    delegator: 'ale.aristeguieta',
    delegatee: 'nutbox.mine',
    vesting_shares: '2292864.177587 VESTS',
    _address: 'TQhe7ruXm96KfPBP3C5UdJpLU7n5Fijffv',
  }
] Error: Request failed with status code 403
    at createError (.../node_modules/tronweb/node_modules/axios/lib/core/createError.js:16:15)
    at settle (.../node_modules/tronweb/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (.../node_modules/tronweb/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1223:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
```

The temporary fix would be:

1. retry when detecting error messages in the pattern of containing `status code 403`, but the message is a bit vague and may cause false alarm. 
2. in the web UI, remind a user to try re-delegate if the staking didn't succeed after N seconds.

**Comment by alearisteguieta** [comment]
Ok, the second option may be the more alternative option. The question is that, for example, the user will be charged two fees, one for the failed transaction and the other for the transaction that was validated.

**Comment by ssnam90** [comment]
I am currently experiencing the same phenomenon (@ssnam90).

**Comment by terryyyyyy** [comment]
The increase delegation operation will based on user's origin steem delegation.
